# syntax=docker/dockerfile:1

# Control plane CLI tools for EJFAT
#
# This is a two-stage build, with compile and deploy stages

#
# Stage 'base': image with dependencies
#
FROM ubuntu:22.04 AS base

ENV DISTRO=ubuntu22
ENV HOME=/home/ubuntu
ENV LD_LIBRARY_PATH=/usr/local/lib
ENV PATH=/usr/local/bin:$PATH
ENV E2SARINSTALL=/e2sar-install
ENV DEPSVER=0.1.0
ENV DEPSDEB=e2sar-deps_0.1.0_amd64.deb

RUN apt-get -yq update && apt-get -yq install python3-pip build-essential autoconf cmake libtool pkg-config libglib2.0-dev ninja-build openssl libssl-dev libsystemd-dev protobuf-compiler libre2-dev gdb

RUN pip3 install pybind11 scapy meson

#
# Stage 'compile'
#
FROM base AS compile

WORKDIR /src

COPY . /src/

# blow away build/ if it got copied by accident
RUN rm -rf build/

# download and install boost and grpc deps
RUN curl -Ls https://github.com/JeffersonLab/E2SAR/releases/download/E2SAR-$DEPSVER-ubuntu-22.04/$DEPSDEB > $DEPSDEB  
RUN dpkg -i $DEPSDEB

# create a build configuration
RUN BOOST_ROOT=/usr/local meson setup -Dpkg_config_path=/usr/local/lib/pkgconfig/ --prefix $E2SARINSTALL build

# compile
RUN meson compile -C build

# install
RUN meson install -C build

ENTRYPOINT ["tail", "-f", "/dev/null"]