# syntax=docker/dockerfile:1

#
# Single-stage development container for E2SAR - contains compiler, debugger and other tools
#

FROM ubuntu:22.04 AS base

ENV DISTRO=ubuntu22
ENV HOME=/home/ubuntu
ENV LD_LIBRARY_PATH=/usr/local/lib
ENV PATH=/usr/local/bin:$PATH
ENV DEPSVER=0.1.0
ENV DEPSDEB=e2sar-deps_0.1.0_amd64.deb

RUN apt-get -yq update && apt-get -yq install python3-pip build-essential autoconf cmake libtool pkg-config libglib2.0-dev ninja-build openssl libssl-dev libsystemd-dev protobuf-compiler libre2-dev gdb curl git vim

RUN pip3 install pybind11 scapy meson

RUN apt-get install git-lfs && git lfs install 

#
# Stage 'compile'
#
FROM base AS compile

WORKDIR /src

COPY ./docker-dev-entrypoint.sh /src/docker-dev-entrypoint.sh

# download and install boost and grpc deps
RUN curl -Ls https://github.com/JeffersonLab/E2SAR/releases/download/E2SAR-$DEPSVER-ubuntu-22.04/$DEPSDEB > $DEPSDEB  
RUN dpkg -i $DEPSDEB

ENTRYPOINT ["/src/docker-dev-entrypoint.sh"]

CMD ["setup_src"]