#include "fec/rs_encode.h"
#include <cassert>

namespace fec {

// ---------------------------------------------------------------------------
// GF(16) lookup tables — generated by prototype/python/genMatrix_simplified.py
//
// Field: GF(2^4), irreducible polynomial x^4 + x + 1 (= 0b10011).
// Primitive element: alpha (the root of the polynomial).
//
// gf_log[i]  = alpha^i  (exponent i → field element)    range [0,14]: i < 15
// gf_exp[x]  = log_alpha(x)  (field element x → exponent)  gf_exp[0] = 15 (sentinel)
// ---------------------------------------------------------------------------
static constexpr uint8_t gf_log[16] = { 1,2,4,8,3,6,12,11,5,10,7,14,15,13,9,0 };
static constexpr uint8_t gf_exp[16] = { 15,0,1,4,2,8,5,10,3,14,9,7,6,13,11,12 };

// ---------------------------------------------------------------------------
// RS(10,8) parity sub-matrix P (transposed from G = [I_8 | P])
//
// Element-space values (from rs_model.h):
//   P column 0: { 14, 6, 14,  9,  7, 1, 15, 6 }
//   P column 1: {  5, 9,  4, 13,  8, 1,  5, 8 }
//
// Pre-converted to exponent space (gf_exp[element]) for fast encoding:
//   All coefficients are non-zero, so no zero guard is needed for them —
//   only the zero check on the data symbol is required.
// ---------------------------------------------------------------------------
static constexpr uint8_t coeff0_exp[8] = { 11, 5, 11, 14, 10, 0, 12, 5 };
static constexpr uint8_t coeff1_exp[8] = {  8,14,  2, 13,  3, 0,  8, 3 };

// ---------------------------------------------------------------------------
// rs_encode
//
// Iterates over every 5-byte codeword in the buffer. For each codeword:
//   1. Extracts 8 GF(16) data symbols from bytes 0-3 (nibble-packed pairs).
//   2. Computes 2 parity symbols using the generator matrix parity columns.
//   3. Packs the 2 parity symbols into byte 4.
//
// GF multiplication: a * b = alpha^(log(a) + log(b)) mod 15
//   Special case: a == 0 → product is 0 (coefficients are all non-zero).
// GF addition: a + b = a ^ b (characteristic-2 field).
// ---------------------------------------------------------------------------
void rs_encode(std::span<uint8_t> codewords, const FecBlockParams& params)
{
    assert(codewords.size() == params.codeword_buf_size());

    const uint32_t nw = params.num_words();
    uint8_t* cw = codewords.data();

    for (uint32_t w = 0; w < nw; ++w, cw += FecBlockParams::CODEWORD_BYTES) {
        // Extract 8 data nibbles from bytes 0-3.
        // Even-indexed symbols occupy the high nibble; odd-indexed the low nibble.
        const uint8_t sym[8] = {
            static_cast<uint8_t>((cw[0] >> 4) & 0xFu),   // symbol 0
            static_cast<uint8_t>( cw[0]        & 0xFu),   // symbol 1
            static_cast<uint8_t>((cw[1] >> 4) & 0xFu),   // symbol 2
            static_cast<uint8_t>( cw[1]        & 0xFu),   // symbol 3
            static_cast<uint8_t>((cw[2] >> 4) & 0xFu),   // symbol 4
            static_cast<uint8_t>( cw[2]        & 0xFu),   // symbol 5
            static_cast<uint8_t>((cw[3] >> 4) & 0xFu),   // symbol 6
            static_cast<uint8_t>( cw[3]        & 0xFu),   // symbol 7
        };

        // Compute parity0 = XOR_{j=0..7} gf_mul(P[j][0], sym[j])
        // Compute parity1 = XOR_{j=0..7} gf_mul(P[j][1], sym[j])
        //
        // Using pre-converted exponent-space coefficients for speed:
        //   gf_mul(coeff, s) = (s == 0) ? 0 : gf_log[(gf_exp[s] + coeff_exp) % 15]
        uint8_t p0 = 0u;
        uint8_t p1 = 0u;
        for (int j = 0; j < 8; ++j) {
            if (sym[j] != 0u) {
                const uint8_t es = gf_exp[sym[j]];
                p0 ^= gf_log[static_cast<uint8_t>((es + coeff0_exp[j]) % 15u)];
                p1 ^= gf_log[static_cast<uint8_t>((es + coeff1_exp[j]) % 15u)];
            }
        }

        cw[4] = static_cast<uint8_t>((p0 << 4u) | p1);
    }
}

} // namespace fec

// =============================================================================
// ARM NEON implementation
// =============================================================================
#if defined(__ARM_NEON)
#include <arm_neon.h>

namespace fec {

// ---------------------------------------------------------------------------
// rs_encode_neon
//
// Processes 8 codewords per NEON iteration — one codeword per uint8x8_t lane.
// Each outer iteration handles one 40-byte group (8 × 5-byte codewords):
//
//   1. Gather  — stride-5 lane-insert loads → 4 NEON vectors (one per data byte)
//   2. Split   — vshr/vand → 8 nibble streams (hi and lo for each data byte)
//   3. Encode  — vtbl2/vadd/mod15/vtbl2/vbic/veor pipeline for 2 parity acc.
//   4. Pack    — vorr → parity byte; vst1_lane scatter → byte 4 of each codeword
//
// GF(16) operations:
//   Multiply: vtbl2_u8(exp_tbl, data) gets exponents; vadd_u8 adds coefficient
//             exponent; vcge/vand/vsub does branchless mod 15; vtbl2_u8(log_tbl)
//             converts back to element space.
//   Zero mask: vceq_u8(data, 0) + vbic_u8 forces product to 0 when data == 0.
//   Addition:  veor_u8 (GF addition is XOR in characteristic-2 fields).
//
// The function shares the GF(16) tables and coefficient arrays already defined
// at file scope in the scalar rs_encode() above.
// ---------------------------------------------------------------------------

// GF multiply helper: data_exp = vtbl2_u8(exp_tbl, data) pre-computed.
// zm = vceq_u8(data, zero) — 0xFF where data is 0 (to force product = 0).
// ce = coefficient exponent (compile-time constant for each call site).
static inline uint8x8_t gf_mul_ne(const uint8x8x2_t& log_tbl, uint8x8_t data_exp,
                                   uint8x8_t zm, uint8_t ce, uint8x8_t mod15)
{
    const uint8x8_t sum     = vadd_u8(data_exp, vdup_n_u8(ce));
    const uint8x8_t exp_sum = vsub_u8(sum, vand_u8(mod15, vcge_u8(sum, mod15)));
    return vbic_u8(vtbl2_u8(log_tbl, exp_sum), zm);
}

void rs_encode_neon(std::span<uint8_t> codewords, const FecBlockParams& params)
{
    assert(codewords.size() == params.codeword_buf_size());

    // GF(16) tables as uint8x8x2_t: vtbl2_u8 treats two 8-byte vectors as a
    // single 16-entry lookup table.  index >= 16 returns 0 (unused here since
    // GF(16) symbols and exponents are always in [0,15]).
    const uint8x8x2_t exp_tbl = {{ vld1_u8(gf_exp),     vld1_u8(gf_exp + 8) }};
    const uint8x8x2_t log_tbl = {{ vld1_u8(gf_log),     vld1_u8(gf_log + 8) }};
    const uint8x8_t   zero    = vdup_n_u8(0u);
    const uint8x8_t   mod15   = vdup_n_u8(15u);
    const uint8x8_t   nibmask = vdup_n_u8(0x0Fu);

    uint8_t* base = codewords.data();
    const uint32_t ch = params.col_height;

    // Outer loop: one 40-byte group (8 codewords) per byte_idx.
    // num_words() = col_height * 8, so there are exactly col_height groups.
    for (uint32_t byte_idx = 0; byte_idx < ch; ++byte_idx, base += 40u) {

        // -----------------------------------------------------------------
        // Step 1: Gather — lane-insert loads
        //
        // Codeword i starts at base + i*5; byte j of codeword i is at base + i*5 + j.
        // GATHER_BYTE(j) builds a uint8x8_t where lane i = byte j of codeword i.
        // The nested form evaluates right-to-left (innermost = lane 7, outermost = lane 0).
        // -----------------------------------------------------------------
#define GATHER_BYTE(j)                                                         \
    vld1_lane_u8(base + 0*5+(j), vld1_lane_u8(base + 1*5+(j),                 \
    vld1_lane_u8(base + 2*5+(j), vld1_lane_u8(base + 3*5+(j),                 \
    vld1_lane_u8(base + 4*5+(j), vld1_lane_u8(base + 5*5+(j),                 \
    vld1_lane_u8(base + 6*5+(j), vld1_lane_u8(base + 7*5+(j),                 \
    zero, 7), 6), 5), 4), 3), 2), 1), 0)

        const uint8x8_t d0 = GATHER_BYTE(0);  // byte 0 of all 8 codewords
        const uint8x8_t d1 = GATHER_BYTE(1);  // byte 1
        const uint8x8_t d2 = GATHER_BYTE(2);  // byte 2
        const uint8x8_t d3 = GATHER_BYTE(3);  // byte 3
#undef GATHER_BYTE

        // -----------------------------------------------------------------
        // Step 2: Nibble split
        // h0 = symbol 0 (high nibble of d0), l0 = symbol 1 (low nibble of d0)
        // h1 = symbol 2, l1 = symbol 3, h2 = symbol 4, l2 = symbol 5
        // h3 = symbol 6, l3 = symbol 7
        // Each vector has 8 lanes: lane i = that symbol's value in codeword i.
        // -----------------------------------------------------------------
        const uint8x8_t h0 = vshr_n_u8(d0, 4),  l0 = vand_u8(d0, nibmask);
        const uint8x8_t h1 = vshr_n_u8(d1, 4),  l1 = vand_u8(d1, nibmask);
        const uint8x8_t h2 = vshr_n_u8(d2, 4),  l2 = vand_u8(d2, nibmask);
        const uint8x8_t h3 = vshr_n_u8(d3, 4),  l3 = vand_u8(d3, nibmask);

        // -----------------------------------------------------------------
        // Pre-compute exp-table lookups and zero masks for all 8 symbol streams.
        // exp lookup is shared between the two parity computations.
        // -----------------------------------------------------------------
        const uint8x8_t eh0 = vtbl2_u8(exp_tbl, h0), zmh0 = vceq_u8(h0, zero);
        const uint8x8_t el0 = vtbl2_u8(exp_tbl, l0), zml0 = vceq_u8(l0, zero);
        const uint8x8_t eh1 = vtbl2_u8(exp_tbl, h1), zmh1 = vceq_u8(h1, zero);
        const uint8x8_t el1 = vtbl2_u8(exp_tbl, l1), zml1 = vceq_u8(l1, zero);
        const uint8x8_t eh2 = vtbl2_u8(exp_tbl, h2), zmh2 = vceq_u8(h2, zero);
        const uint8x8_t el2 = vtbl2_u8(exp_tbl, l2), zml2 = vceq_u8(l2, zero);
        const uint8x8_t eh3 = vtbl2_u8(exp_tbl, h3), zmh3 = vceq_u8(h3, zero);
        const uint8x8_t el3 = vtbl2_u8(exp_tbl, l3), zml3 = vceq_u8(l3, zero);

        // Shorthand — log_tbl and mod15 are captured from the outer scope.
        auto gmul = [&](uint8x8_t de, uint8x8_t zm, uint8_t ce) -> uint8x8_t {
            return gf_mul_ne(log_tbl, de, zm, ce, mod15);
        };

        // -----------------------------------------------------------------
        // Step 3: GF multiply-accumulate — 8 codewords in parallel per lane
        //
        // Parity 0 — coeff0_exp: {11, 5, 11, 14, 10, 0, 12, 5}
        //            for symbols: {h0, l0,  h1,  l1, h2, l2, h3, l3}
        // Parity 1 — coeff1_exp: { 8,14,  2, 13,  3, 0,  8,  3}
        // -----------------------------------------------------------------
        uint8x8_t acc0 =                 gmul(eh0, zmh0, 11);
        acc0 = veor_u8(acc0,             gmul(el0, zml0,  5));
        acc0 = veor_u8(acc0,             gmul(eh1, zmh1, 11));
        acc0 = veor_u8(acc0,             gmul(el1, zml1, 14));
        acc0 = veor_u8(acc0,             gmul(eh2, zmh2, 10));
        acc0 = veor_u8(acc0,             gmul(el2, zml2,  0));
        acc0 = veor_u8(acc0,             gmul(eh3, zmh3, 12));
        acc0 = veor_u8(acc0,             gmul(el3, zml3,  5));

        uint8x8_t acc1 =                 gmul(eh0, zmh0,  8);
        acc1 = veor_u8(acc1,             gmul(el0, zml0, 14));
        acc1 = veor_u8(acc1,             gmul(eh1, zmh1,  2));
        acc1 = veor_u8(acc1,             gmul(el1, zml1, 13));
        acc1 = veor_u8(acc1,             gmul(eh2, zmh2,  3));
        acc1 = veor_u8(acc1,             gmul(el2, zml2,  0));
        acc1 = veor_u8(acc1,             gmul(eh3, zmh3,  8));
        acc1 = veor_u8(acc1,             gmul(el3, zml3,  3));

        // -----------------------------------------------------------------
        // Step 4: Pack parity nibbles and scatter to byte 4 of each codeword.
        // acc0/acc1 are GF(16) elements ∈ [0,15] so high bits are already zero;
        // vand with nibmask is defensive only.
        // parity_byte[i] = (acc0[i] << 4) | acc1[i]
        // -----------------------------------------------------------------
        const uint8x8_t par_byte = vorr_u8(vshl_n_u8(vand_u8(acc0, nibmask), 4),
                                            vand_u8(acc1, nibmask));

        vst1_lane_u8(base +  4, par_byte, 0);  // codeword 0, byte 4
        vst1_lane_u8(base +  9, par_byte, 1);  // codeword 1, byte 4
        vst1_lane_u8(base + 14, par_byte, 2);
        vst1_lane_u8(base + 19, par_byte, 3);
        vst1_lane_u8(base + 24, par_byte, 4);
        vst1_lane_u8(base + 29, par_byte, 5);
        vst1_lane_u8(base + 34, par_byte, 6);
        vst1_lane_u8(base + 39, par_byte, 7);  // codeword 7, byte 4
    }
}

} // namespace fec

#endif // __ARM_NEON
