{% set version = load_file_regex(load_file='../VERSION.txt', regex_pattern="^(.*)$", from_recipe_dir=True)[0] %}

package:
  name: e2sar
  version: {{ version }}

source:
  path: ..

build:
  number: {{ environ.get('CONDA_BUILD_NUMBER', '1') }}
  string: "h{{ PKG_HASH }}_py{{ python }}_{{ PKG_BUILDNUM }}"
  script:
    - export BOOST_ROOT=$PREFIX
    - export CXXFLAGS="-std=c++17 -Wno-c++26-extensions"
    - meson setup --prefix $PREFIX -Dpkg_config_path=$PREFIX/lib/pkgconfig build --wipe
    - meson compile -C build -j 2
    - meson install -C build

requirements:
  build:
    - {{ compiler('cxx') }}
    - meson
    - ninja
    - pkg-config
  host:
    - python
    - libboost-devel ==1.89.0
    - libboost ==1.89.0
    - libgrpc >=1.74.1
    - libprotobuf
    - protobuf
    - pybind11
  run:
    - {{ pin_compatible('python', max_pin='x.x') }}
    - {{ pin_compatible('libgrpc', max_pin='x.x') }}
    - {{ pin_compatible('libprotobuf', max_pin='x.x') }}
    - {{ pin_compatible('libboost', max_pin='x.x') }}
    - numpy

about:
  home: https://github.com/JeffersonLab/E2SAR
  license_file:
    - LICENSE
  summary: E2SAR Event Segmentation And Reassembly library
