{% set version = load_file_regex(load_file='../VERSION.txt', regex_pattern="^(.*)$", from_recipe_dir=True)[0] %}

package:
  name: e2sar
  version: {{ version }}

source:
  path: ..

build:
  number: 5
  string: "h{{ PKG_HASH }}_py{{ python }}_{{ PKG_BUILDNUM }}"
  script:
    - export BOOST_ROOT=$BUILD_PREFIX
    - export CXXFLAGS="-std=c++17 -Wno-c++26-extensions"
    - meson setup --prefix $PREFIX -Dpkg_config_path=$BUILD_PREFIX/lib/pkgconfig build --wipe
    - meson compile -C build -j 2
    - meson install -C build

requirements:
  build:
    - {{ compiler('cxx') }}
    - python
    - meson
    - ninja
    - boost-cpp ==1.85.0, <1.87.0
    - grpc-cpp >=1.51.1
    - protobuf
    - pybind11
    - libstdcxx-ng
  run:
    - {{ pin_compatible('python', max_pin='x.x') }}
    - {{ pin_compatible('grpc-cpp', max_pin='x.x') }}
    - {{ pin_compatible('protobuf', max_pin='x.x') }}
    - {{ pin_compatible('libstdcxx-ng', max_pin='x') }}
    - {{ pin_compatible('boost-cpp', max_pin='x.x') }}
    - numpy

about:
  home: https://github.com/JeffersonLab/E2SAR
  license_file:
    - LICENSE
  summary: E2SAR Event Segmentation And Reassembly library
