#ifndef __ejfat_rs_tables_h
#define __ejfat_rs_tables_h

// ============================================================================
// EJFAT Reed-Solomon GF(16) Lookup Tables and Constants
// ============================================================================
//
// This file contains pre-computed lookup tables for Reed-Solomon encoding
// and decoding operations over GF(16) with irreducible polynomial [1,0,0,1,1].
//
// These tables enable fast Galois Field arithmetic without runtime computation.
// Originally generated by Python prototype (prototype/python/genMatrix_simplified.py)
//
// Configuration: RS(10,8) - 8 data symbols + 2 parity symbols
// ============================================================================

// GF(16) Logarithm Table
// Maps field elements to their discrete logarithm representation
static const char _ejfat_rs_gf_log_seq[16] = {
    1, 2, 4, 8, 3, 6, 12, 11, 5, 10, 7, 14, 15, 13, 9, 0
};

// GF(16) Exponent Table
// Maps discrete logarithms back to field elements
static const char _ejfat_rs_gf_exp_seq[16] = {
    15, 0, 1, 4, 2, 8, 5, 10, 3, 14, 9, 7, 6, 13, 11, 12
};

// GF(16) Multiplication Table
// Direct lookup for a * b = _ejfat_rs_gf_mul_table[a][b]
static const char _ejfat_rs_gf_mul_table[16][16] = {
    { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 },
    { 0, 2, 4, 6, 8, 10, 12, 14, 3, 1, 7, 5, 11, 9, 15, 13 },
    { 0, 3, 6, 5, 12, 15, 10, 9, 11, 8, 13, 14, 7, 4, 1, 2 },
    { 0, 4, 8, 12, 3, 7, 11, 15, 6, 2, 14, 10, 5, 1, 13, 9 },
    { 0, 5, 10, 15, 7, 2, 13, 8, 14, 11, 4, 1, 9, 12, 3, 6 },
    { 0, 6, 12, 10, 11, 13, 7, 1, 5, 3, 9, 15, 14, 8, 2, 4 },
    { 0, 7, 14, 9, 15, 8, 1, 6, 13, 10, 3, 4, 2, 5, 12, 11 },
    { 0, 8, 3, 11, 6, 14, 5, 13, 12, 4, 15, 7, 10, 2, 9, 1 },
    { 0, 9, 1, 8, 2, 11, 3, 10, 4, 13, 5, 12, 6, 15, 7, 14 },
    { 0, 10, 7, 13, 14, 4, 9, 3, 15, 5, 8, 2, 1, 11, 6, 12 },
    { 0, 11, 5, 14, 10, 1, 15, 4, 7, 12, 2, 9, 13, 6, 8, 3 },
    { 0, 12, 11, 7, 5, 9, 14, 2, 10, 6, 1, 13, 15, 3, 4, 8 },
    { 0, 13, 9, 4, 1, 12, 8, 5, 2, 15, 11, 6, 3, 14, 10, 7 },
    { 0, 14, 15, 1, 13, 3, 2, 12, 9, 7, 6, 8, 4, 10, 11, 5 },
    { 0, 15, 13, 2, 9, 6, 4, 11, 1, 14, 12, 3, 8, 7, 5, 10 }
};

// Reed-Solomon Code Parameters
static const int _ejfat_rs_n = 8;   // Number of data symbols
static const int _ejfat_rs_p = 2;   // Number of parity symbols
static const int _ejfat_rs_k = 10;  // Total message length (n + p)

// Reed-Solomon Generator Matrix G[8][10]
// Used for encoding: codeword = data * G
// Format: [I | P] where I is 8x8 identity, P is 8x2 parity
static const char _ejfat_rs_G[8][10] = {
    {1, 0, 0, 0, 0, 0, 0, 0, 14, 5},
    {0, 1, 0, 0, 0, 0, 0, 0, 6, 9},
    {0, 0, 1, 0, 0, 0, 0, 0, 14, 4},
    {0, 0, 0, 1, 0, 0, 0, 0, 9, 13},
    {0, 0, 0, 0, 1, 0, 0, 0, 7, 8},
    {0, 0, 0, 0, 0, 1, 0, 0, 1, 1},
    {0, 0, 0, 0, 0, 0, 1, 0, 15, 5},
    {0, 0, 0, 0, 0, 0, 0, 1, 6, 8}
};

#endif // __ejfat_rs_tables_h
