test : test.c ejfat_rs.h ../prototype/python/rs_model.h
	gcc -o test test.c -O3

test_enc_dec : test_enc_dec.c ejfat_rs.h ejfat_rs_decoder.h ../prototype/python/rs_model.h
	gcc -o test_enc_dec test_enc_dec.c -O3

