name: Build E2SAR dependency artifacts on Rocky 9

on: [push, pull_request]

env:
  GRPC_VER: 1.54.1
  BOOST_VER: 1.85.0
  E2SAR_VER: 0.1.5

jobs:
  distribution-check:
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:9
    steps:
      - name: Are we on rocky linux?
        run: |
          cat /etc/os-release

      - name: Set up environment
        run: |
          sudo yum -yq install epel-release
          sudo yum -yq --enablerepo=devel update
          sudo yum -yq --enablerepo=devel install gcc gcc-c++ kernel-devel make
          sudo yum -yq --enablerepo=devel install python3-pip autoconf cmake libtool pkg-config ninja-build openssl protobuf-compiler glib2-devel re2-devel libquadmath-devel python39-devel python39
        

