name: Build E2SAR dependency artifacts on Rocky 9

on: [push, pull_request]

env:
  GRPC_VER: 1.54.1
  BOOST_VER: 1.85.0
  E2SAR_VER: 0.1.5

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:9.0
    steps:
      - name: Are we on rocky linux?
        run: |
          cat /etc/os-release
          dnf search python3
          dnf search python3 | grep devel

      - name: Set up environment
        run: |
          dnf -yq install epel-release
          dnf -yq --enablerepo=devel update
          dnf -yq --enablerepo=devel install gcc gcc-c++ kernel-devel make
          dnf -yq --enablerepo=devel install python3-pip autoconf cmake libtool pkg-config ninja-build openssl protobuf-compiler glib2-devel re2-devel libquadmath-devel python3-devel python3
          ls /usr/bin | grep python

