permissions:
  contents: write
  
name: Deploy E2sar debs and dependency debs to releases

on:
  workflow_dispatch:
env:
  E2SAR_VER: 0.1.4
  E2SAR_DEP: 1.85.0-boost-1.54.1-grpc

jobs:
  release:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
        
    steps:
      - name: Checkout E2SAR code
        uses: actions/checkout@v4
        with:
          path: E2SAR
          submodules: false
          token: ${{ secrets.CLASSIC_REPO_PAT }}

      - name: Download built boost and grpc artifact
        if: steps.cache.outputs.cache-hit != 'true'  # Only run if cache wasn't hit
        id: download-artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: deps2debs.yml
          name: ${{ matrix.os }}-e2sar-deps-${{ env.E2SAR_VER }}-package
          path: E2SAR

      - name: Download built e2sar deb
        if: steps.cache.outputs.cache-hit != 'true'  # Only run if cache wasn't hit
        id: download-e2sar-deb
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: distro.yml
          name: ${{ matrix.os }}-e2sar-${{ github.ref_name }}-${{ env.E2SAR_VER }}-package
          path: E2SAR

      - name: create GH release
        run: |
          cd E2SAR
          gh release create E2SAR-${{ github.ref_name }}-${{ env.E2SAR_VER }}-${{ matrix.os }} ./*.deb
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash

        
          
