permissions:
  contents: write

name: Deploy E2sar rpms and dependency rpms to releases
on:
  workflow_dispatch:

env:
  GRPC_VER: 1.54.1
  BOOST_VER: 1.85.0
  E2SAR_VER: 0.1.5

jobs:
  build:
    runs-on: ubuntu-latest
      matrix:
        container: ["rockylinux/rockylinux:9.0", "rockylinux/rockylinux:9.5"]
    container:
      image: ${{ matrix.container }}
    permissions:
      contents: write
    steps:

      - name: Install gh
        run: |
          curl -fsSL https://cli.github.com/packages/rpm/gh-cli.repo | tee /etc/yum.repos.d/github-cli.repo
          dnf -y install gh
          gh --version
      - name: Checkout E2SAR code
        uses: actions/checkout@v4
        with:
          path: E2SAR
          submodules: false
          token: ${{ secrets.CLASSIC_REPO_PAT }}

      - name: Download built boost and grpc artifact
        if: steps.cache.outputs.cache-hit != 'true'  # Only run if cache wasn't hit
        id: download-artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: deps2rpm.yml
          name: ${{ matrix.container }}-e2sar-deps-${{ env.E2SAR_VER }}-package
          path: E2SAR

      - name: Download built e2sar rpm
        if: steps.cache.outputs.cache-hit != 'true'  # Only run if cache wasn't hit
        id: download-e2sar-rpm
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: distroRocky.yml
          name: ${{ matrix.container }}-e2sar-${{ github.ref_name }}-${{ env.E2SAR_VER }}-package
          path: E2SAR

      - name: create GH release
        run: |
          cd E2SAR
          gh release create E2SAR-${{ github.ref_name }}-${{ env.E2SAR_VER }}-${{ matrix.container }} ./*.rpm
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
